/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: 'Roboto, sans-serif',
      },
      colors: {
        rosewater: '#f5e0dc',
        flamingo: '#f2cdcd',
        pink: '#f5c2e7',
        mauve: '#cba6f7',
        red: '#f38ba8',
        maroon: '#eba0ac',
        peach: '#fab387',
        yellow: '#f9e2af',
        green: '#a6e3a1',
        teal: '#94e2d5',
        sky: '#89dceb',
        sapphire: '#74c7ec',
        blue: '#89b4fa',
        lavender: '#b4befe',
        text: '#cdd6f4',
        subtext1: '#bac2de',
        subtext0: '#a6adc8',
        overlay2: '#9399b2',
        overlay1: '#7f849c',
        overlay0: '#6c7086',
        surface2: '#585b70',
        surface1: '#45475a',
        surface0: '#313244',
        base: '#1e1e2e',
        mantle: '#181825',
        crust: '#11111b',
        'light-rosewater': '#dc8a78',
        'light-flamingo': '#dd7878',
        'light-pink': '#ea76cb',
        'light-mauve': '#8839ef',
        'light-red': '#d20f39',
        'light-maroon': '#e64553',
        'light-peach': '#fe640b',
        'light-yellow': '#df8e1d',
        'light-green': '#40a02b',
        'light-teal': '#179299',
        'light-sky': '#04a5e5',
        'light-sapphire': '#209fb5',
        'light-blue': '#1e66f5',
        'light-lavender': '#7287fd',
        'light-text': '#4c4f69',
        'light-subtext1': '#5c5f77',
        'light-subtext0': '#6c6f85',
        'light-overlay2': '#7c7f93',
        'light-overlay1': '#8c8fa1',
        'light-overlay0': '#9ca0b0',
        'light-surface2': '#acb0be',
        'light-surface1': '#bcc0cc',
        'light-surface0': '#ccd0da',
        'light-base': '#eff1f5',
        'light-mantle': '#e6e9ef',
        'light-crust': '#dce0e8',
      },
    },
  },
  plugins: [],
};
